GET http://{{base_url}}/book/list
Accept: application/json

###


GET http://{{base_url}}/book/detail/52
Accept: application/json

###

POST http://{{base_url}}/book/create
Content-Type: application/json

{
  "books": [
    {
      "name": "C# 从入门到精通121",
      "authors": [
        {
          "name": "NAT"
        },
        {
          "name": "ZZW"
        }
      ]
    }
  ]
}

###

DELETE http://{{base_url}}/book/delete
Content-Type: application/json

{
  "book_ids": [
    {
      "id": 2
    },
    {
      "id": 3
    }
  ]
}

###

PUT http://{{base_url}}/book/edit/55
Content-Type: application/json

{
  "name": "C# 从入门到精通",
  "authors": [
    {
      "name": "NAT"
    },
    {
      "name": "ZZW"
    }
  ]
}

###