GET http://{{host}}:{{port}}/api/v1/detailbook/52
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/listbook
Accept: application/json

###
POST http://{{host}}:{{port}}/api/v1/addbook
Content-Type: application/json

{
  "books": [
    {
      "name": "C# 从入门到精通11",
      "authors": [
        {
          "name": "NAT"
        },
        {
          "name": "ZZW"
        }
      ]
    }
  ]
}

###

DELETE http://{{host}}:{{port}}/api/v1/delbook
Content-Type: application/json

{
  "book_ids": [
    {
      "id": 2
    },
    {
      "id": 3
    }
  ]
}

###

###
PUT http://{{host}}:{{port}}/api/v1/editbook/55
Content-Type: application/json

{
  "name": "C# 从入门到精通",
  "authors": [
    {
      "name": "NAT"
    },
    {
      "name": "ZZW"
    }
  ]
}

###