[language]
local = "zh-cn"


[mysql]

[mysql.base]
connmaxlifetime = 60
maxidleconn = 60
maxopenconn = 10

[mysql.read]
addr = "127.0.0.1"
port = 3306
name = "book_cloud"
passwd = "bookcloud"
user = "bookcloud"

[mysql.write]
addr = "127.0.0.1"
port = 3306
name = "book_cloud"
passwd = "bookcloud"
user = "bookcloud"

[redis]
addr = "127.0.0.1"
port = 6379
db = "0"
maxretries = 3
minidleconns = 5
pass = ""
poolsize = 10